# Generated by Django 4.1.7 on 2023-03-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=36, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('price', models.FloatField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('current_payment_status', models.CharField(choices=[('0', 'Unknown'), ('1', 'Processed'), ('2', 'Paid')], default='', max_length=24)),
            ],
        ),
    ]
