# Generated by Django 4.1.7 on 2023-03-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_new',
            new_name='Book',
        ),
    ]
